version: "3"
volumes:
  logs.app:
  cache.app:
services:
  nginx:
    container_name: nginx.systeme.io
    build:
      context: ./infrastructure
      dockerfile: Dockerfile_Nginx
    ports:
      - "8000:80"
      - "8001:8081"
    links:
      - php
      - db
    volumes:
      - ./:/app
      - ./infrastructure/host.conf:/etc/nginx/conf.d/default.conf
  php:
    container_name: php.systeme.io
    build:
        context: ./infrastructure
        dockerfile: Dockerfile_PHP
    ports:
        - "9003:9000"
    links:
      - db
    volumes:
      - ./:/app
#    environment:
#      XDEBUG_CONFIG: "remote_host=192.168.220.5 remote_enable=1"
#      PHP_IDE_CONFIG: "serverName=Docker"
  db:
    image: postgres:9.5
    container_name: pgsql.systeme.io
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    ports:
      - 5432:5432
  adminer:
    image: adminer
    container_name: adminer.systeme.io
    restart: always
    ports:
      - 8080:8080
